# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_stealth import stealth

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    stealth(self.driver)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.genmo.ai/")
    self.driver.implicitly_wait(5)
    self.driver.set_window_size(838, 940)
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Ajustify-between").click()
    self.driver.find_element(By.CSS_SELECTOR, ".caret-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".caret-primary").send_keys("make a video of dog wearing bow")
    self.driver.find_element(By.CSS_SELECTOR, ".\\!h-\\[34px\\]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\!h-\\[34px\\]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Ahidden > .group").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-\\[10px\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(1) > .relative > .relative > .card > div > .w-full > .absolute").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .relative > .relative > .card > div > .w-full > .absolute").click()
  
