# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

class TestCreatorTool:
    def setup_method(self, method):
        # Define Chrome options to load a specific Google Chrome profile
        chrome_options = webdriver.ChromeOptions()
        user_data_dir = "C:\\Users\\aryan\\AppData\\Local\\Google\\Chrome\\User Data"  # Path to user data
        chrome_options.add_argument(f"--user-data-dir={user_data_dir}")  # Specify user data directory
        chrome_options.add_argument("--profile-directory=Default")  # Specify the profile directory (e.g., Profile 1)

        # Initialize the WebDriver with the options
        self.driver = webdriver.Chrome(options=chrome_options)
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_creatorTool(self):
        # Define the input text
        input_text = "Create a content for France tourism company"

        # Open the target website
        self.driver.get("https://ai.invideo.io/workspace/f6f2a191-461c-4779-ac0a-074d861f707c/v30-copilot")
        self.driver.set_window_size(584, 960)

        # Interact with the page
        WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located((By.NAME, "brief")))
        self.driver.find_element(By.NAME, "brief").send_keys(input_text)
        self.driver.find_element(By.CSS_SELECTOR, ".c-PJLV-ihwxBsS-css > svg").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-fxmfvX-ijHXML-variant-default").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-eZwudA > .c-cURRIC").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-PJLV:nth-child(1) > .c-PJLV > .c-fxmfvX:nth-child(1) > .c-cURRIC").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-PJLV:nth-child(2) > .c-PJLV > .c-fxmfvX:nth-child(1) > .c-cURRIC").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-fxmfvX-icDCGyM-css").click()

        # Perform action chains
        element = self.driver.find_element(By.CSS_SELECTOR, ".c-fxmfvX-icDCGyM-css")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".c-eCRGRP").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c-eCRGRP").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".c-eCRGRP")
        actions.double_click(element).perform()

        # Close the driver
        self.driver.close()

