# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_stealth import stealth

class TestGenmoAi():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    stealth(self.driver,
      languages=["en-US", "en"],
      vendor="Google Inc.",
      platform="Win32",
      webgl_vendor="Intel Inc.",
      renderer="Intel Iris OpenGL Engine",
      fix_hairline = True)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_genmoAi(self):
    self.driver.get("https://www.genmo.ai/")
    self.driver.set_window_size(584, 960)
    self.driver.find_element(By.CSS_SELECTOR, ".caret-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".caret-primary").send_keys("Make a video on freelancers")
    self.driver.find_element(By.CSS_SELECTOR, ".\\!duration-200 > .font-medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Ahidden > .group").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Ahidden > .group")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .card > div > .w-full > .absolute").click()
    self.driver.close()
  
